### ISSUE TITLE
Loading DSOs with cffi/ctypes

### ISSUE THREAD

**Issue by ktbarrett** [mdavidsaver/setuptools_dso#13]
I see there are solid recommendations for loading DSOs that are linked by extension modules on both Windows and Linux. However, I am interested in producing DSOs to be loaded by the cffi (ABI in-line mode) or ctypes. This is possible on Windows using the same technique (modifying `PATH` or `os.add_dll_directory`), but does not work on Linux. Modifying `LD_LIBRARY_PATH` does not work (as you are probably aware). What's the recommendation for this use case? Computing the full path to the library and making the name available in a support module?

**Comment by mdavidsaver** [comment]
> Computing the full path to the library and making the name available in a support module?

This is what I [have](https://github.com/mdavidsaver/epicscorelibs/blob/3514a9b9705f88cc6073d7c2c869b1cb8245b11c/src/python/epicscorelibs/path/__init__.py#L40) [done](https://github.com/mdavidsaver/epicscorelibs/blob/3514a9b9705f88cc6073d7c2c869b1cb8245b11c/src/python/epicscorelibs/ca/cadef.py#L29).  `__file__` works well as a starting point.  The only tedious part is the prefix/suffix for each target.

**Comment by ktbarrett** [comment]
> This is what I have done.

I see, that is what I had in mind.

> The only tedious part is the prefix/suffix for each target.

Yes, and it's quite tedious, especially once adding MinGW, MSys2, Cygwin, etc. to the mix. Do you think it's worthwhile to file a feature request in Python for extending `os.add_dll_directory` to work in Linux? The interface already exists, might as well milk it for all it's worth. Or is this something that you think this project can solve?

**Comment by mdavidsaver** [comment]
> ... adding MinGW, MSys2, Cygwin, etc. to the mix.

It's been more than a decade since I last inflicted cygwin on myself, so I can't speak for this one.  For the others, the variation is in the import library name possibilities, which are consumed by the compiler.  I believe that the runtime library names, consumed by the Windows OS, must always be `*.dll` with no prefix.

> ... feature request in Python for extending `os.add_dll_directory` to work in Linux?

While I can't speak for the python developers, I suspect that this idea would be better received if it came with a prototype implementation.  `os.add_dll_directory()` is wrapping [AddDllDirectory()](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory), which changes the behavior of `LoadLibrary()`.  To my knowledge, there is no equivalent way to effect the search path of `dlopen()` after a process has started.  While this could to some degree be emulated in the python stdlib, it would be an incomplete solution effecting only those `dlopen()` calls made through these wrappers.

> Or is this something that you think this project can solve?

This depends a bit on what you have in mind.  An interface for computing platform specific library prefix/suffix would be reasonable, trying to patch `ctypes` would be a harder sell.

While the example I linked above is using information obtained from `distutils.sysconfig` to decide what the library prefix/suffix should be, another possibility would be a dynamic search.  Since the library root name is under control, and there will only be one in a given installation, a couple of `glob.glob()` calls might suffice.  eg. something like

```py
from glob import glob
def get_lib(base, paths):
    for path in paths:
        for pat in ('%s.so', '%s.dylib', '%s.dll'):
            match = glob(os.path.join(path, pat%base))
            if match:
                return match[0]
    raise RuntimeError('%s not found'%base)
```

**Comment by mdavidsaver** [comment]
fyi.  `sys.platform` is simpler than `sysconfig`.

https://github.com/mdavidsaver/setuptools_dso/blob/0adb63b54724f5853dd16c2a6e1726f1b48226c1/src/setuptools_dso/dsocmd.py#L104-L110

**Comment by ktbarrett** [comment]
>  I believe that the runtime library names, consumed by the Windows OS, must always be `*.dll` with no prefix.

mingw-w32/64 use a `lib` prefix. msys2 uses `msys-` prefix for some libraries (for instance it's `msys-python3.8.dll`) and no prefix other times. Conda and the official Python distribution for Windows use no prefix. It's a mess.

Maybe this project could create a Python module during the build phase (like setuptools_scm does with the version module) with code for getting the absolute path to DSOs built by the project.

**Comment by ktbarrett** [comment]
Also I feel like you shouldn't need to make the whole prefix and extension decisions again, distutils *should* have some facility for that, right?

**Comment by mdavidsaver** [comment]
> `msys-python3.8.dll`

Unless I'm missing some magic, this would not be found by [`LoadLibrary("python3.8")`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya) right?  I think this is taking advantage of the fact that the dependency [DLL names](https://stackoverflow.com/questions/477461/when-building-a-dll-file-does-the-generated-lib-file-contain-the-dll-name) which end up in a `.exe` or `.dll` are encoded in the dependency import libraries.  eg. `libpython3.8.dll.a` would contain the string `msys-python3.8.dll`.

> could create a Python module during the build phase

This seems like a reasonable way to go.  I think that such a file could be emitted by `build_dso()` since it already has all of the paths.  The generated file name should be something which has a reasonable chance of avoiding a collision.  eg. `some.lib.mydso` could generate `some/lib/mydso_path.py` (being careful to escape the path string).

https://github.com/mdavidsaver/setuptools_dso/blob/0adb63b54724f5853dd16c2a6e1726f1b48226c1/src/setuptools_dso/dsocmd.py#L335-L344

Is this a change you would be interested in attempting?  If so, I would ask that you extend the [example](https://github.com/mdavidsaver/setuptools_dso/tree/master/example) to test it, at least importing the generated .py and verifying the DSO path.  Either with `os.path.isfile()`, or preferably actually loading.

**Comment by ktbarrett** [comment]
> Unless I'm missing some magic, this would not be found by [`LoadLibrary("python3.8")`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya) right

Right.

> I think this is taking advantage of the fact that the dependency [DLL names](https://stackoverflow.com/questions/477461/when-building-a-dll-file-does-the-generated-lib-file-contain-the-dll-name) which end up in a `.exe` or `.dll` are encoded in the dependency import libraries. eg. `libpython3.8.dll.a` would contain the string `msys-python3.8.dll`.

Likely correct, I don't know what the equivalent of `readelf` is on Windows to confirm. Regardless, you need to know the prefix and extension if you want to load it via another method like `ctypes.CDLL()`, and those values change depending on the environment you are in and who built the library. But ultimately, you can choose whatever scheme you want for setuptools_dso as long as you provide those names directly to users rather than have them have to compute it.

> This seems like a reasonable way to go. I think that such a file could be emitted by `build_dso()` since it already has all of the paths. The generated file name should be something which has a reasonable chance of avoiding a collision. eg. `some.lib.mydso` could generate `some/lib/mydso_path.py` (being careful to escape the path string).

I would probably do a single file with a user configurable name (with a sane default like `{project name}/_dsos.py`) with a single Python dict like so:

```python
dso_info = {
    'original.lib.name': dict(path=f'{root}/original/lib/libname.so'),
    ...
}
```

It will allow more information to be added in the future if need be.

> Is this a change you would be interested in attempting? If so, I would ask that you extend the [example](https://github.com/mdavidsaver/setuptools_dso/tree/master/example) to test it, at least importing the generated .py and verifying the DSO path. Either with `os.path.isfile()`, or preferably actually loading.

I can try, but my understanding of distutils/setuptools internals is weak.

**Comment by mdavidsaver** [comment]
> equivalent of `readelf` is on Windows

Run `dumpbin /all some.lib` and look for "DLL name:".


> a sane default like `{project name}/_dsos.py`

I wonder how sane a single name like this can be.  It would need to account for situations where a build has multiple DSOs (which I have).  Also, while hypothetically, i believe it is possible for one setup.py to install multiple top level packages.

I think I default is reasonable, provided it is emitted into the directory containing the DSO.  This could be one per DSO as I suggest above, or one per directory.

> It will allow more information to be added in the future if need be.

The first thing I would add is a (conditional) call to ` os.add_dll_directory()`, which I guess is an argument for one file per-directory.

> I can try, but my understanding of distutils/setuptools internals is weak.

No nice way to put it.  That code is a ugly mess of old hacks on top of older hacks.  I don't think you would need to dive deep through.  One reason I started with the idea of generating one file per DSO is simplicity.  You can use the existing control flow, and place the info/path file alongside each DSO file (the path in `outlib` local variable).

Some other points:

* The `dso` argument passed to `build_dso.build_dso()` is an instance of `DSO`.

* Files under `self.build_lib` will be installed.

https://github.com/mdavidsaver/setuptools_dso/blob/0adb63b54724f5853dd16c2a6e1726f1b48226c1/src/setuptools_dso/dsocmd.py#L255-L256

I've added some comments which may be helpful b2122025189352ef175e276b37d6a35e59e59868

* Please respect `self.dry_run`

https://github.com/mdavidsaver/setuptools_dso/blob/0adb63b54724f5853dd16c2a6e1726f1b48226c1/src/setuptools_dso/dsocmd.py#L350-L354

* It will also be necessary to handle `self.inplace`.

**Comment by ktbarrett** [comment]
>  Also, while hypothetically, i believe it is possible for one setup.py to install multiple top level packages.

Forgot about that feature... multiple files would be better then. Wouldn't this mean we would also have to generate `__init__.py` files for each directory with a DSO in it so it's importable?

> I think a default is reasonable, provided it is emitted into the directory containing a DSO. This could be one per DSO as I suggest above, or one per directory.

I guess this would be an option fed to `setup` that would specify a file pattern: `dso_info_module="{}_dso.py"` by default.

> The first thing I would add is a (conditional) call to ` os.add_dll_directory()`, which I guess is an argument for one file per-directory.

I don't see anything in the documentation for `AddDllDirectory` that says adding the same directory multiple times would break it. I think multiple files would still be fine. In fact the following statement implies it's kept in an unordered set.

> If AddDllDirectory is used to add more than one directory to the process DLL search path, the order in which those directories are searched is unspecified.

> One reason I started with the idea of generating one file per DSO is simplicity. You can use the existing control flow, and place the info/path file alongside each DSO file (the path in `outlib` local variable).

This is where I will start. Thanks for the additional info! I'll try to get something working by the weekend.

**Comment by mdavidsaver** [comment]
> I think multiple files would still be fine.

I doubt it would break anything.  Load times could be increased unless the impl. is smart enough to ignore duplicates (this is the search path for every dll).  I have some past experience with excessive load times in an environment which combined lengthy `$LD_LIBRARY_PATH` with network storage.

> I guess this would be an option fed to `setup` that would specify a file pattern: `dso_info_module="{}_dso.py"` by default.

Maybe better to make this override an argument of the `DSO` constructor?

> Wouldn't this mean we would also have to generate `__init__.py` files for each directory with a DSO in it so it's importable?

This file would certainly be needed.  I guess it could be generated if it doesn't already exist.  I'm OK with leaving this as a manual step.

**Comment by ktbarrett** [comment]
> Maybe better to make this override an argument of the DSO constructor?

I can't imagine anyone needing that level of control, but I'll do that. 

> I'm OK with leaving this as a manual step.

Yeah, I'm fairly certain setuptools_scm requires this to be done manually, so should we =)

**Comment by mdavidsaver** [comment]
> I can't imagine anyone needing that level of control, but I'll do that.

I never cease to be amazed at how particular some people are about naming.

**Comment by ktbarrett** [comment]
I think this has been addressed.
